### ISSUE TITLE
[BUG REPORT] Virtual Labs Dynamics analysis of Four bar mechanism

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1037]
### **Bug Reported on 9 August, 13:59 GMT +5:50 in** 
Lab - Dynamics of Machine
Experiment - Dynamics analysis of Four bar mechanism
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions
* Simulation Not Working

Additional info- Simulation hangs and changing value is difficult. Error before putting all values saying not satisfy.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://dom-nitk.vlabs.ac.in/exp/four-bar-mechanism/simulation.html
Email - praphulla678@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1723192184098.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Unable to reproduce. Additional details required to analyze further
