### ISSUE TITLE
[BUG REPORT] Compression Test Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1047]
### **Bug Reported on 10 August, 16:24 GMT +5:50 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Compression Test Experiment
**Type(s) of Issue -**
* Insufficient Content

Additional info- Good 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/compression-test-experiment/
Email - khandukachare289@gmail.com

**Comment by shraddha** [comment]
This is more of a feedback than a bug, hence marking it invalid and closing it.
