### ISSUE TITLE
[BUG REPORT] Position analysis of Elliptical Trammel

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1385]
### **Bug Reported on 24 August, 18:46 GMT +5:50 in** 
Lab - Mechanics of Machine
Experiment - Position analysis of Elliptical Trammel
**Type(s) of Issue -**
* Content Not Visible

Additional info- Hshi

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36
Experiment Link - https://mm-nitk.vlabs.ac.in/exp/position-analysis-elliptical-trammel/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITR1724505308332.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
The issue screenshot is not relevant to the experiment. Hence closing the issue with label **Inappropriate**
