### ISSUE TITLE
[BUG REPORT] Virtual Labs Double Acting Reciprocating Pump

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1646]
### **Bug Reported on 2 September, 17:26 GMT +8:0 in** 
Lab - Fluid Machinery Lab
Experiment - Double Acting Reciprocating Pump
**Type(s) of Issue -**
* Simulation Not Working

Additional info- it doesnt want to start

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://fmc-nitk.vlabs.ac.in/exp/reciprocating-pump/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1725268987765.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
The type of issue mentioned and the screenshot shared are not relevant. Hence closing the issue as **Inappropriate**
