### ISSUE TITLE
[BUG REPORT] Virtual Labs EXCEPTION HANDLING

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#174]
### **Bug Reported on 21 November, 12:13 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - EXCEPTION HANDLING
**Type(s) of Issue -**
* Incorrect Results/Observations
* Simulation Not Working

Additional info- Handling exceptions is not correct for ZeroDivisionException

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by shraddha** [comment]
This lab is not hosted yet, hence marking it as invalid and closing it.
