### ISSUE TITLE
[BUG REPORT] Flow through packed bed

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1813]
### **Bug Reported on 7 September, 13:19 GMT +5:50 in** 
Lab - Process Control & Reaction Engineering and Unit Operations Lab
Experiment - Flow through packed bed
**Type(s) of Issue -**
* Simulation Not Working
* Incorrect Results/Observations

Additional info- Always shows change manometer fluid 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://uorepc-nitk.vlabs.ac.in/exp/flow-through-packed-bed/simulation.html

**Comment by SOLVE-NITK** [comment]
Unable to reproduce. Additional details are required to analyze further
