### ISSUE TITLE
[BUG REPORT] Compression Test on Spring Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1884]
### **Bug Reported on 10 September, 12:50 GMT +5:50 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Compression Test on Spring Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation not working 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/compression-test-spring-experiment/simulation.html
Email - arufk4794@gmail.com

**Comment by shraddha** [comment]
The simulation seems to be working fine, hence marking as Not Reproducible and closing it.
