### ISSUE TITLE
[BUG REPORT] Control Of Bus Voltages Through Onload Tap Changes

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#1885]
### **Bug Reported on 10 September, 14:10 GMT +5:50 in** 
Lab - Virtual Substation Automation Lab
Experiment - Control Of Bus Voltages Through Onload Tap Changes
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/537.36 (KHTML, like Gecko) Safari/537.36 VivoBrowser/12.8.2.0 Chrome/87.0.4280.141
Experiment Link - https://sa-nitk.vlabs.ac.in/exp/onload-tap-changes/simulation.html

**Comment by SOLVE-NITK** [comment]
Unable to reproduce. Additional details are required to analyze further.
