### ISSUE TITLE
[BUG REPORT] Virtual Labs Whitworth Mechanism

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#196]
### **Bug Reported on 25 March, 20:49 GMT +5:50 in** 
Lab - Mechanics of Machine II
Experiment - Whitworth Mechanism
**Type(s) of Issue -**
* Content Not Visible

Additional info- I am writing to express my frustration regarding the visibility and scrolling options for the content. Currently, half of the content is not visible, and there is no scrolling option available. This has made it difficult for me to access the complete information. I would appreciate it if this issue could be addressed promptly. Thank you for your attention to this matter.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1711379961653.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
The entire template has been converted to the responsive format
