### ISSUE TITLE
[BUG REPORT] Performance Characteristics of Hydraulic Ram

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2002]
### **Bug Reported on 13 September, 19:43 GMT +5:50 in** 
Lab - Fluid Machinery Lab
Experiment - Performance Characteristics of Hydraulic Ram
**Type(s) of Issue -**
* Page Not Loading
* Insufficient Content
* Content Not Visible
* Incorrect Content

Additional info- Lab

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Experiment Link - https://fmc-nitk.vlabs.ac.in/exp/hydraulic-ram/

**Comment by SOLVE-NITK** [comment]
Issue is not clear. No email-id is provided to clarify further. So closing the issue with the label 'Inappropriate'
