### ISSUE TITLE
[BUG REPORT] Virtual Labs Impact Test on Aggregate

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#2055]
### **Bug Reported on 19 September, 15:5 GMT +5:50 in** 
Lab - Transportation Engineering
Experiment - Impact Test on Aggregate
**Type(s) of Issue -**

Additional info- good

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://ts-nitk.vlabs.ac.in/exp/impact-test/simulation.html

**Comment by SOLVE-NITK** [comment]
Not an issue.
