### ISSUE TITLE
[BUG REPORT] Virtual Labs LEAF AREA INDEX

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#21]
### **Bug Reported on 6 September, 16:18 IST in** 
Lab - Virtual Lab
Experiment - LEAF AREA INDEX
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation is not loading
Experiment Link - https://virtual-labs.github.io/exp-leaf-area-index-meter-nitk/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1662461299720.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Simulation loading was delayed and now the issue is fixed.

**Comment by SOLVE-NITK** [comment]
Simulation Loading was delayed while testing and Now the issue is fixed.
