### ISSUE TITLE
[BUG REPORT] Virtual Labs Column Analysis Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#258]
### **Bug Reported on 9 May, 15:1 GMT +5:50 in** 
Lab - Basic Structural Analysis
Experiment - Column Analysis Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Experiment Link - https://bsa-iiith.vlabs.ac.in/exp/column-analysis/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1715247101577.png" alt="Issue image">

**Comment by shraddha** [comment]
The simulations are done in flash. The simulation is not showing at all. Hence marking it as a bug.
