### ISSUE TITLE
[BUG REPORT] Virtual Labs FLOW THROUGH PIPES

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#286]
### **Bug Reported on 23 May, 12:38 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - FLOW THROUGH PIPES
**Type(s) of Issue -**
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Experiment Link - https://virtual-labs.github.io/exp-flow-through-pipes-nitk/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1716448060366.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Duplicate. This issue has already been reported in #1350. Closing this to consolidate the discussion there.
