### ISSUE TITLE
[BUG REPORT] Virtual Labs Dynamic Vibration Absorber

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#307]
### **Bug Reported on 18 June, 21:6 GMT -3:0 in** 
Lab - Machine Dynamics and Vibration Lab
Experiment - Dynamic Vibration Absorber
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Experiment Link - https://mdmv-nitk.vlabs.ac.in/exp/exp-dynamic-vibration-absorber-nitk/simulation.html
Email - pwilliam90@hotmail.com.br
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1718755595492.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Duplicate. This issue has already been reported in #2516. Closing this to consolidate the discussion there.
