### ISSUE TITLE
[BUG REPORT] Virtual Labs Performance Characteristics of Kaplan Turbine

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3244]
### **Bug Reported on 15 October, 15:3 GMT +5:50 in** 
Lab - Fluid Machinery Lab
Experiment - Performance Characteristics of Kaplan Turbine
**Type(s) of Issue -**
* Simulation Not Working

Additional info- it is not working even after pressing the start button

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://fmc-nitk.vlabs.ac.in/exp/kaplan-turbine/simulation.html

**Comment by SOLVE-NITK** [comment]
Duplicate. This issue has already been reported in #373. Closing this to consolidate the discussion there.
