### ISSUE TITLE
[BUG REPORT] Measurement of Self Inductance of High Quality Factor Coil by Hay's Bridge

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3273]
### **Bug Reported on 16 October, 12:26 GMT +5:50 in** 
Lab - Analog Signals Network and Measurement Virtual Laboratory
Experiment - Measurement of Self Inductance of High Quality Factor Coil by Hay's Bridge
**Type(s) of Issue -**
* Page Not Loading

Additional info- css uda gayi aapki

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://asnm-iitkgp.vlabs.ac.in/exp/high-quality-factor-coil
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IITKGP1729061793050.png" alt="Issue image">

**Comment by ravikiran2020** [comment]
Duplicate issue
