### ISSUE TITLE
[BUG REPORT] Path algorithms: Dijkstraâs shortest path

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3338]
### **Bug Reported on 17 October, 13:28 GMT +5:50 in** 
Lab - Data Structures - 2
Experiment - Path algorithms: Dijkstraâs shortest path
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- Shraddha testing - please delete the bug

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://ds2-iiith.vlabs.ac.in/exp/dijkstra-algorithm/index.html

**Comment by shraddha** [comment]
This is a test bug and hence closing it.
