### ISSUE TITLE
[BUG REPORT] Data Clustering: K-Means, MST-based

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3343]
### **Bug Reported on 17 October, 13:35 GMT +5:50 in** 
Lab - Pattern recognition
Experiment - Data Clustering: K-Means, MST-based
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading

Additional info- Shraddha testing - please delete the bug

UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Experiment Link - https://cse20-iiith.vlabs.ac.in/exp/mst-based/
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1729152322724.png" alt="Issue image">

**Comment by shraddha** [comment]
This is created as a testing bug, hence closing.
