### ISSUE TITLE
[BUG REPORT] Determination of Flouride in water

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3382]
### **Bug Reported on 18 October, 6:6 GMT +2:0 in** 
Lab - Environmental Engineering 2
Experiment - Determination of Flouride in water
**Type(s) of Issue -**
* Insufficient Content
* Page Not Loading
* Content Not Visible
* Incorrect Content

Additional info- 0958214576

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36
Experiment Link - https://ee2-nitk.vlabs.ac.in/exp/flouride-in-water/procedure.html

**Comment by SOLVE-NITK** [comment]
Page is loading properly. Simulation is working. Unable to reproduce. Additional details required to analyze further.
