### ISSUE TITLE
[BUG REPORT] Built-in Modules

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3535]
### **Bug Reported on 22 October, 15:24 GMT +5:50 in** 
Lab - Python Programming Lab
Experiment - Built-in Modules
**Type(s) of Issue -**
* Incorrect Content

Additional info- fgiukijhbjrfuythgnljlkliyjfgffuck

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://python-iitk.vlabs.ac.in/exp/built-in-modules/theory.html

**Comment by vlabiitk** [comment]
Resolved
