### ISSUE TITLE
[BUG REPORT] Virtual Labs Implementation Of PLC Arithmatic Instructions

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3812]
### **Bug Reported on 2 November, 21:26 GMT +5:50 in** 
Lab - Virtual Programmable Logic Controller Lab
Experiment - Implementation Of PLC Arithmatic Instructions
**Type(s) of Issue -**
* Simulation Not Working

Additional info- After adding a rung and inserting a open contact [], I cannot select or add any arithmetic operations as given in the procedure, no response when I click on the ADD or any other operations.

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Experiment Link - https://plc-coep.vlabs.ac.in/exp/plc-arithmatic-instructions/simulation.html
Email - rk0566248@gmail.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/COEP1730562979521.png" alt="Issue image">

**Comment by ravikiran2020** [comment]
Duplicate issue
