### ISSUE TITLE
[BUG REPORT] Ouchterlony Double Diffusion -Titration

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3903]
### **Bug Reported on 6 November, 11:41 GMT +5:50 in** 
Lab - Immunology Virtual Lab II
Experiment - Ouchterlony Double Diffusion -Titration
**Type(s) of Issue -**
* Insufficient Content

Additional info- UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://ivl2-au.vlabs.ac.in/exp/ouchterlony-double-diffusion-titration/
Email - testing bug
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/AMRT1730873493789.png" alt="Issue image">

**Comment by priya100raman** [comment]
It is bug that was created for testing purposes
