### ISSUE TITLE
[BUG REPORT] Virtual Labs MIPS Assembly Language Programming - 1

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#3972]
### **Bug Reported on 7 November, 12:44 GMT +5:0 in** 
Lab - Computer Organisation
Experiment - MIPS Assembly Language Programming - 1
**Type(s) of Issue -**
* Simulation Not Working
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Experiment Link - https://cse11-iiith.vlabs.ac.in/exp/mips1/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1730965461539.png" alt="Issue image">

**Comment by ravikiran2020** [comment]
Duplicate issue of #3971
