### ISSUE TITLE
[BUG REPORT] Pipe Bursting

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4105]
### **Bug Reported on 13 November, 11:59 GMT +5:50 in** 
Lab - Fluid Machinery Lab
Experiment - Pipe Bursting
**Type(s) of Issue -**
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Experiment Link - https://fmc-nitk.vlabs.ac.in/exp/pipe-bursting/procedure.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1731479449127.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Page is loading and simulation is working properly. _For info_: User has to click on the "Ok" button to proceed further. Unable to reproduce. Additional details required to analyze further.
