### ISSUE TITLE
[BUG REPORT] Fatigue Test Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4311]
### **Bug Reported on 21 November, 10:17 GMT +5:50 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Fatigue Test Experiment
**Type(s) of Issue -**

Additional info- Fatigue test experiment 

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/fatigue-test-experiment/
Email - diparathod1101@gmail.com

**Comment by shraddha** [comment]
This is duplicate of https://github.com/virtual-labs/bugs-virtual-labs/issues/1900 Hence closing.
