### ISSUE TITLE
[BUG REPORT] Virtual Labs Structural Geology: Analysis of Dip and Strike

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4556]
### **Bug Reported on 3 December, 14:39 GMT +5:50 in** 
Lab - Mining Geology
Experiment - Structural Geology: Analysis of Dip and Strike
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Contour map 1 ,step 8

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://mg-nitk.vlabs.ac.in/exp/dip-and-strike/simulation.html

**Comment by SOLVE-NITK** [comment]
The bug is resolved and the experiment link is rehosted.
