### ISSUE TITLE
[BUG REPORT] Virtual Labs Thickness of Strata by Graphical Method

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4735]
### **Bug Reported on 12 December, 13:26 GMT +5:50 in** 
Lab - Mining Geology
Experiment - Thickness of Strata by Graphical Method
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://mg-nitk.vlabs.ac.in/exp/graphical-method/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1733990179181.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
Closing this bug and making https://github.com/virtual-labs/bugs-virtual-labs/issues/4736 as the reference bug for this experiment.
