### ISSUE TITLE
[BUG REPORT] BELLMAN-FORD ALGORITHM

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4758]
### **Bug Reported on 13 December, 9:54 GMT +5:50 in** 
Lab - Virtual Lab
Experiment - BELLMAN-FORD ALGORITHM
**Type(s) of Issue -**
* Page Not Loading
* Insufficient Content
* Page Not Loading

Additional info- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://virtual-labs.github.io/exp-bellman-ford-iiith/index.html
Email - sjkd@akj.com
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1734063891319.png" alt="Issue image">

**Comment by shraddha** [comment]
This is created for testing, hence closing it.

**Comment by shmore-iitg** [comment]
testing.
