### ISSUE TITLE
[BUG REPORT] Virtual Labs Determination of TS,TDS and TSS in water

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4760]
### **Bug Reported on 13 December, 10:19 GMT +5:50 in** 
Lab - Environmental Engineering 1
Experiment - Determination of TS,TDS and TSS in water
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- result after calculation showing wrong

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://ee1-nitk.vlabs.ac.in/exp/determination-of-ts/simulation.html

**Comment by SOLVE-NITK** [comment]
The issue cannot be replicated based on the provided information and email-id is not provided. Hence closing the issue.
