### ISSUE TITLE
[BUG REPORT] Virtual Labs Container Filling Process Using PLC

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4808]
### **Bug Reported on 16 December, 16:12 GMT +5:50 in** 
Lab - Industrial Electric Drives and Application of PLC
Experiment - Container Filling Process Using PLC
**Type(s) of Issue -**
* Simulation Not Working

Additional info- UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Experiment Link - https://ied-nitk.vlabs.ac.in/exp/exp-container-filling-process-nitk/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/NITK1734345765815.png" alt="Issue image">

**Comment by SOLVE-NITK** [comment]
The issue doesn't seem to fit the content with the experiment. Hence marking it as invalid and closing it.
