### ISSUE TITLE
[BUG REPORT] Virtual Labs GOMS Model

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#4862]
### **Bug Reported on 19 December, 13:38 GMT +5:50 in** 
Lab - Creative Design, Prototyping & Experiential Lab
Experiment - GOMS Model
**Type(s) of Issue -**
* Simulation Not Working

Additional info- stop buttonnot working

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Experiment Link - https://cpe-iitg.vlabs.ac.in/exp/goms-model/simulation.html

**Comment by IITGVLABS** [comment]
Could not reproduce the bug
