### ISSUE TITLE
[BUG REPORT] Virtual Labs Compression Test Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#563]
### **Bug Reported on 22 July, 3:5 GMT -7:0 in** 
Lab - Basic Engineering Mechanics and Strength Of Materials
Experiment - Compression Test Experiment
**Type(s) of Issue -**
* Incorrect Results/Observations

Additional info- it is showing correct values 

UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Experiment Link - https://eerc01-iiith.vlabs.ac.in/exp/compression-test-experiment/simulation.html
**Screenshot of Issue**-<br> <img height="300" src="https://raw.githubusercontent.com/virtual-labs/bugs-virtual-labs/main/IIITH1721642736076.png" alt="Issue image">

**Comment by shraddha** [comment]
This is more of a feedback than a bug, hence closing it.
