### ISSUE TITLE
[BUG REPORT] Weirs Experiment

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#626]
### **Bug Reported on 25 July, 14:50 GMT +5:50 in** 
Lab - Hydraulics and fluid mechanics
Experiment - Weirs Experiment
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Simulation is not working

UserAgent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36
Experiment Link - https://eerc03-iiith.vlabs.ac.in/exp/weirs/simulation.html

**Comment by shraddha** [comment]
Simulation is working as expected, hence marking it as Not Reproducible and closing it.
