### ISSUE TITLE
[BUG REPORT] Flow through fluidized bed

### ISSUE THREAD

**Issue by vlabs-bug** [virtual-labs/bugs-virtual-labs#629]
### **Bug Reported on 25 July, 15:40 GMT +5:50 in** 
Lab - Process Control & Reaction Engineering and Unit Operations Lab
Experiment - Flow through fluidized bed
**Type(s) of Issue -**
* Simulation Not Working

Additional info- Showing service unavailable 

UserAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/124.0.6367.111 Mobile/15E148 Safari/604.1
Experiment Link - https://uorepc-nitk.vlabs.ac.in/exp/flow-through-fluidized-bed/simulation.html
Email - vishwapatel119@gmail.com

**Comment by SOLVE-NITK** [comment]
Unable to reproduce. Additional details are required to analyze further
